name: Run Playwright Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      # 1. Clona o repositório
      - name: Checkout repo
        uses: actions/checkout@v3

      # 2. Instala o Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      # 3. Instala as dependências
      - name: Install dependencies
        run: npm ci

      # 4. Instala os navegadores do Playwright
      - name: Install Playwright Browsers
        run: npx playwright install --with-deps

      # 5. Roda os testes do Playwright
      - name: Run Playwright tests
        run: npx playwright test

      # 6. Gera e publica os relatórios (opcional)
      - name: Upload Playwright report
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: playwright-report
          path: playwright-report

